### Basics

In [41]:
import torch
import numpy as np

In [4]:
x = torch.ones(2, 2, dtype=torch.int)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [9]:
x = torch.ones(2, 3, dtype=torch.float)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [12]:
x, y

(tensor([[0.0163, 0.2281],
         [0.1510, 0.6783]]),
 tensor([[0.0511, 0.4477],
         [0.6379, 0.2399]]))

In [14]:
z = x + y
z

tensor([[0.0674, 0.6759],
        [0.7888, 0.9183]])

In [15]:
y.add_(x)
y

tensor([[0.0674, 0.6759],
        [0.7888, 0.9183]])

In [16]:
z = x / y
z

tensor([[0.2425, 0.3375],
        [0.1914, 0.7387]])

In [17]:
x = torch.empty(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x = torch.tensor([3, 5.2])
x

tensor([3.0000, 5.2000])

In [22]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
x[:, 1]

tensor([2., 5.])

In [24]:
x[1, :]

tensor([4., 5., 6.])

In [26]:
x[1, 2]

tensor(6.)

In [34]:
x[1,2].item()

6.0

The function item() only works when tensor only has one item.

In [35]:
# x[1,:].item()

In [37]:
y = x.view(6)
y

tensor([1., 2., 3., 4., 5., 6.])

In [38]:
y = x.view(3,2)
y

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Use -1 for a dim that should be resolved.

In [39]:
y = x.view(3, -1)
y

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Converting to and from numpy

In [47]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [48]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

If the tensor a is on cpu, not the gpu, both a and b will share the memory, so changes in one will be visible by the other.

In [49]:
a.add_(1)
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

Same thing if we convert from tensor numpy if they are on cpu, they are references to same value in memory.

In [52]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [53]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [54]:
a += 1
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

We should check if gpu is available

In [57]:
torch.cuda.is_available()

True

In [61]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z

In [62]:
z

tensor([2., 2., 2., 2., 2.], device='cuda:0')

We can bring it back to cpu.

In [63]:
z = z.to('cpu')
z

tensor([2., 2., 2., 2., 2.])

In [64]:
z = z.to(device)
z

tensor([2., 2., 2., 2., 2.], device='cuda:0')